### PR TITLE
support async callback

### PR DESCRIPTION
**Pull request by flyingsky**

### CODE REVIEW

**Comment by stoeffel** [comment]
@flyingsky hi thx for the pr. Could you add some tests for this? There was already someone working on this. See https://github.com/joshheyse/gulp-param and https://github.com/joshheyse/gulp-param/pull/1

// cc @joshheyse

**Comment by flyingsky** [comment]
Test case is added. I think it's easy to put callback as the last argument to follow node.js callback convention.

**Comment by stoeffel** [comment]
the test is failing on travis.
yop, the cb as the last arg is fin.

**Comment by stoeffel** [comment]
See https://github.com/joshheyse/gulp-param/blob/master/index.js#L25.
Your implementation doesn't work correctly for your test case.

**Comment by flyingsky** [comment]
I notice this code doesn't work, i will fix it later.

**Comment by stoeffel** [comment]
> I notice this code doesn't work, i will fix it later.

Np, no need to hurry.

**Comment by stoeffel** [comment]
closed via #16

**Pull request closed without merging**
