### PR TITLE
use assignIn to extend gulp

### PR DESCRIPTION
**Pull request by stoeffel**
//cc @przemcio How do you like this?

### CODE REVIEW

**Comment by przemcio** [comment]
Great. Funny because I wanted to send you a proposition with load-dash when I get back to work

**Comment by stoeffel** [comment]
:smile: Just had some time.

**Comment by przemcio** [comment]
So we can merge and release ?

**Comment by stoeffel** [comment]
Jop :deciduous_tree:

**Comment by stoeffel** [comment]
This will again be a breaking change.
```js
var gulp = require('gulp');

gulpParam(gulp, process.argv); // because gulp-param changed the original gulp

gulp.task('dep', function(foo, moo) {
  console.log(foo);
  console.log(moo);
  if (foo) 
    console.log('Hello');
});
```

So we should go for 2.0.0

**Comment by przemcio** [comment]
Actually the code is return extend({}, gulp, { task: wrappedTask }); so the extended object is returned and the original gulp will not be touch at all,  see load dash document
_.assign(object, [sources])
This method mutates object  

So in our case "object" is {}

**Comment by stoeffel** [comment]
What I meant is currently this was possible: 
```js
var gulp = require('gulp');
gulpParam(gulp, process.argv);
```
and with this changes not. Because as you said it will not mutate gulp.
```js
var gulp = require('gulp');
var wrapped = gulpParam(gulp, process.argv);
// gulp !== wrapped
```
so this should be a 2.0.0 release.

**Comment by przemcio** [comment]
OK. Now I get it :)

**Comment by stoeffel** [comment]
Cool. I will release v2. Thanks for your contributions.

**Comment by przemcio** [comment]
I see two more improvements ;)  first is to change this ugly  for (var i = 0; i < functionArguments.length; i++) to be more functional style and the second is to change logging message and use gulp-util

**Comment by stoeffel** [comment]
> I see two more improvements ;) first is to change this ugly for (var i = 0; i < functionArguments.length; i++) to be more functional style and the second is to change logging message and use gulp-util

great idea. I will wait with publishing until we made those changes.

**Pull request merged**
