### PR TITLE
Fix a problem with async callback

### PR DESCRIPTION
**Pull request by przemcio**
- Refactoring the code
- Adding proper handling of async argument 
- Change in documentation.

### CODE REVIEW

**Comment by stoeffel** [comment]
Great work!

**Comment by stoeffel** [comment]
I added you as a maintainer

**Comment by stoeffel** [comment]
published with v1.0.0 :tada: 
Thanks again

**Comment by stoeffel** [comment]
What's your npm username? Will add you there as well.

**Comment by przemcio** [comment]
The same. przemcio
30.01.2016 9:59 AM "Christoph Hermann" <notifications@github.com>
napisał(a):

**Comment by stoeffel** [comment]
Done. Added you as a maintainer to npm.

**Pull request merged**
