### PR TITLE
Remove ugly for loop #19

### PR DESCRIPTION
**Pull request by przemcio**

### CODE REVIEW

**Comment by przemcio** [comment]
What about add code coverage report via codecov ?

**Comment by stoeffel** [comment]
LGTM :deciduous_tree:

**Comment by przemcio** [comment]
I can add it in code but you need to attach codecov into your github account

**Comment by stoeffel** [comment]
Done. I connected my account to codecov

**Comment by stoeffel** [comment]
I have some more ideas to cleanup the code even more. Will try to find some time today or tomorrow.

**Comment by przemcio** [comment]
You are taking about this nasty handing of arguments in wrappedtask?
05.02.2016 10:16 AM "Christoph Hermann" <notifications@github.com>
napisał(a):

**Comment by stoeffel** [comment]
jop

**Pull request merged**
